site_description: "Vue.js - The Progressive JavaScript Framework"
google_analytics: UA-46852172-1
root_domain: vuejs.org
vue_version: 2.5.16

platinum_sponsors_china:
  - url: https://studio.qcloud.coding.net/campaign/favorite-plugins/?utm_source=vue.js&utm_content=cs-logo
    img: cloudstudio.png
  - url: http://www.dcloud.io/?hmsr=vuejsorg&hmpl=&hmcu=&hmkw=&hmci=
    img: dcloud.gif

special_sponsors:
  - url: https://stdlib.com/
    img: stdlib.png
    description: Build APIs you need in minutes instead of days, for free.

platinum_sponsors:
  - url: https://www.bitsrc.io/?utm_source=vue&utm_medium=vue&utm_campaign=vue&utm_term=vue&utm_content=vue
    img: bit-wide.png
    alt_img: bit.png
  - url: http://tooltwist.com/
    img: tooltwist.png
    name: tooltwist
  - url: https://vueschool.io/?utm_source=Vuejs.org&utm_medium=Banner&utm_campaign=Sponsored%20Banner&utm_content=V1
    img: vueschool.png
    name: vue school
  - url: https://vehikl.com/
    img: vehikl.png
    name: vehikl
  - url: https://www.nativescript.org/vue?utm_source=vue-js-org&utm_medium=website&utm_campaign=nativescript-awareness
    img: nativescript.png
    name: nativescript

gold_sponsors:
  - url: https://www.vuemastery.com/
    img: vuemastery.png
    name: vue mastery
  - url: https://laravel.com
    img: laravel.png
    name: laravel
  - url: https://htmlburger.com
    img: htmlburger.png
    name: html burger
  - url: https://chaitin.cn/en/
    img: chaitin.png
    name: chaitin
  - url: https://www.frontenddeveloperlove.com/
    img: frontend-love.png
    name: frontend love
  - url: https://onsen.io/vue/
    img: onsen-ui.png
    name: onsen ui
  - url: https://vuetifyjs.com
    img: vuetify.png
    name: vuetify
  - url: https://neds.com.au/
    img: neds.png
    name: neds
  - url: https://icons8.com/
    img: icons8.png
    name: icons 8
  - url: https://www.valuecoders.com
    img: valuecoders.png
    name: value coders dot org
  - url: https://vuejobs.com/?ref=vuejs
    img: vuejobs.png
    name: vue jobs
  - url: https://tidelift.com/subscription/npm/vue
    img: tidelift.png
    name: tidelift
  - url: https://webdock.io/en
    img: webdock.png
    name: webdock
  - url: https://syncfusion.com/products/vue
    img: syncfusion.png
    name: syncfusion
  - url: https://opteo.com/vue
    img: opteo.png
    name: opteo
  - url: https://devsquad.com/
    img: devsquad.png
    name: dev squad
  - url: https://www.inkoop.in/
    img: inkoop.png
    name: inkoop
  - url: https://www.firesticktricks.com/
    img: firesticks.png
    name: firestick tricks
  - url: https://github.com/marcus-hiles
    img: marcushiles.png
    name: Marcus Hiles
  - url: https://isleofcode.com/
    img: ioc.png
    name: Isle of Code

silver_sponsors:
  - url: https://dopamine.bg/
    img: dopamine.png
    name: dopamine
  - url: https://gridsome.org/
    img: gridsome.png
    name: gridsome

bronze_sponsors:
  - url: http://tighten.co/
    img: http://i.imgur.com/T7fQYLT.png
    name: tighten co
  - url: https://alligator.io
    img: https://alligator.io/images/alligator-logo.svg
    name: alligator dot io
  - url: https://www.accelebrate.com/
    img: https://www.accelebrate.com/assets/images/accelebrate_logo@2x.png
    name: accelebrate
  - url: https://pullstring.com
    img: https://i.imgur.com/hQHW6TB.png
    name: pull string
  - url: https://www.earthlink.ro
    img: https://i.imgur.com/qX0SNa7.png
    name: earthlink
  - url: https://polyglotengineer.com/derek.pollard
    img: https://polyglotengineer.com/DP.png
    name: Derek Pollard
